CREATE DATABASE QLPT
USE QLPT

-- CAU 1 DE 102
CREATE TABLE PHONGTRO(
MaPT CHAR(5) PRIMARY KEY,
TenPT NVARCHAR(50),
DienTich FLOAT,
GiaPT MONEY,
TinhTrangPT NVARCHAR(20)
)

CREATE TABLE CUDAN(
MaCD CHAR(5) PRIMARY KEY,
HoTen NVARCHAR(50),
CCCD NVARCHAR(12),
DiaChi NVARCHAR(100),
SoDT VARCHAR (15),
NgayThue SMALLDATETIME,
TrangThaiCD NVARCHAR(15)
)

CREATE TABLE HOPDONG(
MaHD CHAR(5) PRIMARY KEY,
MaCD CHAR(5),
MaPT CHAR(5),
NgayKy SMALLDATETIME,
NgayHetHan SMALLDATETIME,
TrangThaiHD NVARCHAR(20)
)

CREATE TABLE DICHVU(
MaDV CHAR(5) PRIMARY KEY,
TenDV NVARCHAR(50),
DonGia MONEY
)

CREATE TABLE PHIEUTINHTIEN(
MaPTT CHAR(5) PRIMARY KEY,
MaHD CHAR(5),
SoTienDichVu MONEY,
SoTienThuePT MONEY,
TongTienTT MONEY,
NgayTinhTien SMALLDATETIME,
TinhTrangTT NVARCHAR(20),
PhuongThucTT NVARCHAR(20)
)

CREATE TABLE CHITIETTTDV(
MaPTT CHAR(5),
MADV CHAR(5),
ChiSoDV FLOAT,
ThanhTien MONEY,
PRIMARY KEY(MaPTT, MADV)
)

ALTER TABLE HOPDONG ADD CONSTRAINT FK_MaCD FOREIGN KEY(MaCD) REFERENCES CUDAN(MaCD)
ALTER TABLE HOPDONG ADD CONSTRAINT FK_MaPT FOREIGN KEY(MaPT) REFERENCES PHONGTRO(MaPT)
ALTER TABLE PHIEUTINHTIEN ADD CONSTRAINT FK_MaHD FOREIGN KEY(MaHD) REFERENCES HOPDONG(MaHD)
ALTER TABLE CHITIETTTDV ADD CONSTRAINT FK_MaPTT FOREIGN KEY(MaPTT) REFERENCES PHIEUTINHTIEN(MaPTT)
ALTER TABLE CHITIETTTDV ADD CONSTRAINT FK_MaDV FOREIGN KEY(MADV) REFERENCES DICHVU(MaDV)

-- CAU 2.1
ALTER TABLE PHONGTRO
ADD CONSTRAINT CHECK_GiaPT
CHECK (GiaPT BETWEEN 500000 AND 20000000)

-- CAU 2.2
ALTER TABLE CUDAN
ADD CONSTRAINT CHECK_TrangThaiCD
CHECK (TrangThaiCD IN (N'Đang ở', N'Đã rời đi'))

-- CAU 3.1
SELECT CUDAN.MaCD, CUDAN.HoTen, PHONGTRO.MaPT, PHONGTRO.TenPT
FROM CUDAN, PHONGTRO, HOPDONG
WHERE HOPDONG.MaCD = CUDAN.MaCD 
AND PHONGTRO.MaPT = HOPDONG.MaPT 
AND HOPDONG.TrangThaiHD = N'Đã hết hạn'
AND YEAR(HOPDONG.NgayHetHan) = 2024
