CREATE DATABASE QLPT
USE QLPT

-- CAU 1 DE 102
CREATE TABLE PHONGTRO(
MaPT CHAR(5) PRIMARY KEY,
TenPT NVARCHAR(50),
DienTich FLOAT,
GiaPT MONEY,
TinhTrangPT NVARCHAR(20)
)

CREATE TABLE CUDAN(
MaCD CHAR(5) PRIMARY KEY,
HoTen NVARCHAR(50),
CCCD NVARCHAR(12),
DiaChi NVARCHAR(100),
SoDT VARCHAR (15),
NgayThue SMALLDATETIME,
TrangThaiCD NVARCHAR(15)
)

CREATE TABLE HOPDONG(
MaHD CHAR(5) PRIMARY KEY,
MaCD CHAR(5),
MaPT CHAR(5),
NgayKy SMALLDATETIME,
NgayHetHan SMALLDATETIME,
TrangThaiHD NVARCHAR(20)
)

CREATE TABLE DICHVU(
MaDV CHAR(5) PRIMARY KEY,
TenDV NVARCHAR(50),
DonGia MONEY
)

CREATE TABLE PHIEUTINHTIEN(
MaPTT CHAR(5) PRIMARY KEY,
MaHD CHAR(5),
SoTienDichVu MONEY,
SoTienThuePT MONEY,
TongTienTT MONEY,
NgayTinhTien SMALLDATETIME,
TinhTrangTT NVARCHAR(20),
PhuongThucTT NVARCHAR(20)
)

CREATE TABLE CHITIETTTDV(
MaPTT CHAR(5),
MADV CHAR(5),
ChiSoDV FLOAT,
ThanhTien MONEY,
PRIMARY KEY(MaPTT, MADV)
)

ALTER TABLE HOPDONG ADD CONSTRAINT FK_MaCD FOREIGN KEY(MaCD) REFERENCES CUDAN(MaCD)
ALTER TABLE HOPDONG ADD CONSTRAINT FK_MaPT FOREIGN KEY(MaPT) REFERENCES PHONGTRO(MaPT)
ALTER TABLE PHIEUTINHTIEN ADD CONSTRAINT FK_MaHD FOREIGN KEY(MaHD) REFERENCES HOPDONG(MaHD)
ALTER TABLE CHITIETTTDV ADD CONSTRAINT FK_MaPTT FOREIGN KEY(MaPTT) REFERENCES PHIEUTINHTIEN(MaPTT)
ALTER TABLE CHITIETTTDV ADD CONSTRAINT FK_MaDV FOREIGN KEY(MADV) REFERENCES DICHVU(MaDV)

-- CAU 2.1
ALTER TABLE PHONGTRO
ADD CONSTRAINT CHECK_GiaPT
CHECK (GiaPT BETWEEN 500000 AND 20000000)

-- CAU 2.2
ALTER TABLE CUDAN
ADD CONSTRAINT CHECK_TrangThaiCD
CHECK (TrangThaiCD IN (N'Đang ở', N'Đã rời đi'))

-- CAU 3.1
SELECT CUDAN.MaCD, CUDAN.HoTen, PHONGTRO.MaPT, PHONGTRO.TenPT
FROM CUDAN, PHONGTRO, HOPDONG
WHERE HOPDONG.MaCD = CUDAN.MaCD 
AND PHONGTRO.MaPT = HOPDONG.MaPT 
AND HOPDONG.TrangThaiHD = N'Đã hết hạn'
AND YEAR(HOPDONG.NgayHetHan) = 2024


-- CAU 3.2 Tìm các hợp đồng (mã hợp đồng, mã phòng trọ) đã thanh toán các phiếu tính tiền trong
-- năm 2024 nhưng không sử dụng dịch vụ nào có chỉ số từ 5 trở lên trong những chi tiết của
-- phiếu tính tiền đó

SELECT DISTINCT HOPDONG.MaHD, HOPDONG.MaPT
FROM HOPDONG
JOIN PHIEUTINHTIEN ON HOPDONG.MaHD = PHIEUTINHTIEN.MaHD
WHERE PHIEUTINHTIEN.TinhTrangTT = N'Đã thanh toán'
AND YEAR(PHIEUTINHTIEN.NgayTinhTien) = 2024
AND NOT EXISTS (
	SELECT *
	FROM CHITIETTTDV
	WHERE CHITIETTTDV.MaPTT = PHIEUTINHTIEN.MaPTT
	AND CHITIETTTDV.ChiSoDV >= 5
)

-- CAU 3.3 Tìm thông tin các dịch vụ (mã, tên dịch vụ) có đơn giá trên 10,000 VNĐ và có trong chi
-- tiết của tất cả các phiếu tính tiền ngày 15/12/2024
SELECT DV.MaDV, DV.TenDV
FROM DICHVU DV
WHERE DV.DonGia > 10000
AND NOT EXISTS (
	SELECT PTT.MaPTT
	FROM PHIEUTINHTIEN PTT
	WHERE PTT.NgayTinhTien = '2024-12-15'
	AND NOT EXISTS (
		SELECT 1
		FROM CHITIETTTDV CTDV
		WHERE CTDV.MaPTT = PTT.MaPTT AND CTDV.MADV = DV.MaDV
	)
)

-- CAU 3.4 Với mỗi hợp đồng đã hết hạn, hãy cho biết số lượng phiếu tính tiền trong năm 2024 đã
-- được thanh toán. Thông tin hiển thị: Mã hợp đồng, mã cư dân, số lượng
SELECT HD.MaHD, HD.MaCD, COUNT (PTT.MaPTT) AS SOLUONGPTT
FROM HOPDONG HD
LEFT JOIN PHIEUTINHTIEN PTT 
ON HD.MaHD = PTT.MaHD
AND YEAR(PTT.NgayTinhTien) = 2024
AND PTT.TinhTrangTT = N'Đã thanh toán'
WHERE HD.TrangThaiHD = N'Đã hết hạn'
GROUP BY HD.MaHD, HD.MaCD

-- CAU 3.5 Trong các cư dân có số lần ký hợp đồng ít nhất, tìm cư dân (mã, họ tên) có tổng số tiền
-- đã thanh toán trong năm 2024 nhiều hơn 5,000,000 VNĐ.
SELECT CD.MaCD, CD.HoTen
FROM CUDAN CD
JOIN HOPDONG HD ON HD.MaCD = CD.MaCD
JOIN PHIEUTINHTIEN PTT ON HD.MaHD = PTT.MaHD
WHERE YEAR(PTT.NgayTinhTien) = 2024
AND PTT.TinhTrangTT = N'Đã thanh toán'
AND CD.MaCD IN (
	SELECT MaCD
	FROM HOPDONG
	GROUP BY MaCD
	HAVING COUNT (*) = (
		SELECT MIN(SOLANKIHD)
		FROM (
			SELECT COUNT (*) AS SOLANKIHD
			FROM HOPDONG
			GROUP BY MaCD
		)AS T
	)
)
GROUP BY CD.MaCD, CD.HoTen
HAVING SUM (PTT.TongTienTT) > 5000000
