CREATE DATABASE QLPT
USE QLPT

CREATE TABLE PHONGTRO(
MaPT CHAR(5) PRIMARY KEY,
TenPT NVARCHAR(50),
DienTich FLOAT,
GiaPT MONEY,
TinhTrangPT NVARCHAR(20)
)

CREATE TABLE CUDAN(
MaCD CHAR(5) PRIMARY KEY,
HoTen NVARCHAR(50),
CCCD NVARCHAR(12),
DiaChi NVARCHAR(100),
SoDT VARCHAR (15),
NgayThue SMALLDATETIME,
TrangThaiCD NVARCHAR(15)
)

CREATE TABLE HOPDONG(
MaHD CHAR(5) PRIMARY KEY,
MaCD CHAR(5),
MaPT CHAR(5),
NgayKy SMALLDATETIME,
NgayHetHan SMALLDATETIME,
TrangThaiHD NVARCHAR(20)
)

CREATE TABLE DICHVU(
MaDV CHAR(5) PRIMARY KEY,
TenDV NVARCHAR(50),
DonGia MONEY
)

CREATE TABLE PHIEUTINHTIEN(
MaPTT CHAR(5) PRIMARY KEY,
MaHD CHAR(5),
SoTienDichVu MONEY,
SoTienThuePT MONEY,
TongTienTT MONEY,
NgayTinhTien SMALLDATETIME,
TinhTrangTT NVARCHAR(20),
PhuongThucTT NVARCHAR(20)
)

CREATE TABLE CHITIETTTDV(
MaPTT CHAR(5),
MADV CHAR(5),
ChiSoDV FLOAT,
ThanhTien MONEY,
PRIMARY KEY(MaPTT, MADV)
)

ALTER TABLE HOPDONG ADD CONSTRAINT FK_MaCD FOREIGN KEY(MaCD) REFERENCES CUDAN(MaCD)
ALTER TABLE HOPDONG ADD CONSTRAINT FK_MaPT FOREIGN KEY(MaPT) REFERENCES PHONGTRO(MaPT)
ALTER TABLE PHIEUTINHTIEN ADD CONSTRAINT FK_MaHD FOREIGN KEY(MaHD) REFERENCES HOPDONG(MaHD)
ALTER TABLE CHITIETTTDV ADD CONSTRAINT FK_MaPTT FOREIGN KEY(MaPTT) REFERENCES PHIEUTINHTIEN(MaPTT)
ALTER TABLE CHITIETTTDV ADD CONSTRAINT FK_MaDV FOREIGN KEY(MADV) REFERENCES DICHVU(MaDV)